'''
Author: fuchy@stu.pku.edu.cn
Description: Prepare data for traning and testing.
             *.mat is generated by dataPrepare from *.ply
             *.mat data structure cell{N*4} :
                N: point clouds number; N=1 in '*.mat'
                    {
                        [TreePoints*K*C] Octree data sequence generated from PQ (Quantized point cloud): N*K*C [n,7,6] array
                                         N[n treepoints]  K[7 ancestors]   C[oct code,level,octant,position(xyz)]
                4:      {Location} Original geometric coordinate P (n*3)
                        {qs,offset,Lmax,name} side information; Quantized point cloud PQ = (P-offset)/qs; The depth of PQ; The name of P (point cloud)
                    }
All rights reserved.
'''
import glob
from Preparedata.data import dataPrepare
from networkTool import CPrintl

# Function to create a sorted list of files matching the pattern in 'dir'
def makedFile(dir):
    fileList = sorted(glob.glob(dir))
    return fileList

# Main execution block
if __name__ == "__main__":

    ###### For MPEG, MVUB ######
    oriDir = '/8iVFBv2/longdress/Ply/*.ply'  # Directory containing original .ply point cloud files
    outDir = 'Data/Obj/train/'              # Directory where .mat files will be saved
    ptNamePrefix = 'MPEG_'                  # Prefix for naming saved .mat files ('MVUB_' for MVUB dataset)

    printl = CPrintl('Preparedata/makedFileObj.log')  # Logger for recording processed files
    makeFileList = makedFile(outDir + '*.mat')        # Get list of already processed .mat files
    fileList = sorted(glob.glob(oriDir))              # List of all .ply files to process

    # Iterate through each .ply file
    for n, file in enumerate(fileList):
        fileName = file.split('/')[-1][:-4]                       # Extract file name without extension
        dataName = outDir + ptNamePrefix + fileName + '.mat'     # Path for saving processed file

        if dataName in makeFileList:       # Skip processing if file already exists
            print(dataName, 'maked!')
            continue

        # Process the .ply file and save as .mat
        dataPrepare(file, saveMatDir=outDir, ptNamePrefix=ptNamePrefix, offset=0, rotation=False)

        # NOTE: Set `rotation=True` in the `dataPrepare` function when processing MVUB data

        # Log progress every 10 files
        if n % 10 == 0:
            printl(dataName)
